Update build-release.yml

diff --git a/.github/workflows/build-release.yml b/.github/workflows/build-release.yml
--- a/.github/workflows/build-release.yml
+++ b/.github/workflows/build-release.yml
@@ -82,7 +82,7 @@ jobs:
       - name: Enable corepack
         run: |
           corepack enable
-          corepack prepare yarn@latest --activate
+          corepack prepare yarn@stable --activate
           curl -L https://raw.githubusercontent.com/dimaslanjaka/nodejs-package-types/refs/heads/main/.yarnrc-template.yml -o .yarnrc.yml
 
       - name: Set env
@@ -260,8 +260,12 @@ jobs:
             fi
           fi
 
+      - name: Clean
+        run: npm run clean
+
       - name: Build
         run: npm run build
+
       - name: Pack
         run: npm run pack --if-present
 
@@ -295,18 +299,27 @@ jobs:
           git add release || true
           git add dist || true
           git add lib || true
-      - run: git add postinstall.js packer.js .github
-        if: steps.changes.outputs.files_changed == 'true'
-        continue-on-error: true
       - run: git pull -X theirs
         name: Pull before push
         if: steps.changes.outputs.files_changed == 'true'
-        continue-on-error: true
       - name: Git push
         if: steps.changes.outputs.files_changed == 'true'
-        continue-on-error: true
+        shell: bash
         run: |
           if [ $(git diff --cached --name-only | wc -l) -gt "0" ]; then
+            echo "Staged files and their sizes:"
+            for file in $(git diff --cached --name-only); do
+              if [ -f "$file" ]; then
+                size_bytes=$(stat -c%s "$file")
+                size_mb=$((size_bytes / 1024 / 1024))
+                echo "${size_mb}MB $file"
+                if [ "$size_mb" -gt 30 ]; then
+                  echo "Error: $file exceeds 30MB ($size_mb MB). Aborting push."
+                  exit 1
+                fi
+              fi
+
+            done
             git commit -m "chore: update build from ${{ env.GITHUB_COMMIT_URL }}" -m "commit hash: ${{ env.GITHUB_SHA_SHORT }}" -m "commit url: ${{ env.GITHUB_COMMIT_URL }}" -m "runner: ${{ env.GITHUB_RUNNER_URL }}"
             git push
           fi
